name: Publish
run-name: ${{ github.actor }} triggered a publication
on:
  - workflow_dispatch
  - workflow_call
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    container: 
      image: rebornos/rebornos:latest
      ports:
        - 80
      options: --privileged
    steps:
      - id: init_docker_step
        name: Initialize Docker Container        
        run: sh /usr/bin/init-rebornos-docker.sh
      - id: checkout_repository_step
        name: Checkout Git Repository
        uses: actions/checkout@v3
      - id: build_iso_step
        name: Build the ISO
        run: sh scripts/build.sh              
      - id: upload_iso_artifact_step
        name: Upload the ISO Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: built-iso
          path: output/rebornos*.iso
      - id: create_release_step
        name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - id: upload_release_asset_step
        name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_step.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./rebornos*.iso
          asset_name: rebornos-xfce-minimal.iso
          asset_content_type: application/ISO

